package ch08;

//class ExceptionEx10 {
//    public static void main(String[] args) {
//        throw new Exception();      // Exception을 고의로 발생시킨다
//    }
//}
//
//
////  throw를 받아 줄 catch가 없어서 에러뜸